architecture: replicaset
resources:
  limits:
    cpu: 2500m
    memory: 2Gi
  requests:
    cpu: 500m 
    memory: 600Mi
auth:
  enabled: true
tls:
  enabled: false
replicaCount: 3
persistence:
  storageClass: "premium-rwo"
  size: 1Gi
metrics:
  enabled: true