apiVersion: v1
kind: Service
metadata:
  name: webserv
spec:
  ports:
    - port: 80
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Mi
## kubectl get pods -w -l app=nginx
## kubectl get pvc
## www-web-0   Bound    pvc-ab92bef1-fb85-4108-ad19-9f5deb9c86d7   5Mi        RWO            standard       9m26s
## www-web-1   Bound    pvc-f5d058b4-11be-4010-8e47-13eaa6b5dfee   5Mi        RWO            standard       9m23s
## www-web-2   Bound    pvc-732f9627-687d-4fb7-9b81-31aa87e24d7f   5Mi        RWO            standard       9m21s

## kubectl get sc
## standard (default)   k8s.io/minikube-hostpath   Delete          Immediate           false                  5d2h

## kubectl get pods -w -l app=nginx
## kubectl run -it --rm testcom --image alpine -- sh
## kubectl get pod -o wide
