loki:
  commonConfig:
    replication_factor: 1
  auth_enabled: false
minio:
  enabled: true
test:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1
## helm repo add grafana https://grafana.github.io/helm-charts
## helm repo update
## helm search repo grafana
## kubectl create ns loki
## helm upgrade --install --namespace loki logging grafana/loki -f values.yaml --set loki.auth_enabled=false
## Usage:  helm upgrade [RELEASE] [CHART] [flags]
## kubectl -n loki get all
## kubectl get pvc
## helm install --namespace=loki grafana grafana/grafana
## kubectl get secret --namespace loki grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo admin u8Txs5uRnJTlIDcZrzGt5ksVW1tkmR5HxLANd6FT
## info grafana.loki.svc.cluster.local
## info export POD_NAME=$(kubectl get pods --namespace loki -l "app.kubernetes.io/name=grafana,app.kubernetes.io/instance=grafana" -o jsonpath="{.items[0].metadata.name}")
## info     kubectl --namespace loki port-forward $POD_NAME 3000
## helm install --namespace loki --set loki.serviceName=loki-gateway promtail grafana/promtail
## kubectl port-forward --namespace loki service/grafana 3000:80
## go http://localhost:3000
## got to http://loki-gateway.loki.svc.cluster.local
## helm install prometheus prometheus-community/prometheus -n loki
