apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: zu*k&#YE^{0jFLy78(q
## *.secret.yaml in git ignore :)
## kubectl exec -it pod/mysql-statefulset-0 -- bash
## mysql -u root -p
## Pomme123;
## ALTER USER 'root'@'%' IDENTIFIED BY 'zu*k&#YE^{0jFLy78(q';
##
## kubectl apply -f k8s/
## kubectl delete pods --all
