apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Bonjour ! C'est le CronJob !"
          restartPolicy: OnFailure
  ## kubectl get cronjob simple-cronjob
