apiVersion: batch/v1
kind: Job
metadata:
  name: exemple-job
spec:
  template:
    spec:
      containers:
        - name: job-container
          image: busybox
          command: ["echo", "Bonjour du Job test"]
      restartPolicy: Never
## kubectl apply -f mon-premier-job.yaml
## kubectl get jobs
## kubectl get pods
## kubectl logs exemple-job-rrb9t
