apiVersion: apps/v1
kind: Deployment
metadata:
  name: projet1-html-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: dymafr/projet1-html
        ports:
        - containerPort: 80