apiVersion: v1
kind: Pod
metadata:
  name: demo-cpu-2
spec:
  containers:
    - name: demo-cpu-conteneur-2
      image: vish/stress
      resources:
        limits:
          cpu: "100"
        requests:
          cpu: "100"
## kubectl describe pod demo-cpu-2
## 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
## kubectl delete pod demo-cpu-2
