apiVersion: v1
kind: Pod
metadata:
  name: mon-pod
spec:
  containers:
    - name: mon-conteneur
      image: mon-image
      resources:
        requests:
          memory: "64Mi"
        limits:
          memory: "128Mi"
