apiVersion: v1
kind: Pod
metadata:
  name: demo-cpu
spec:
  containers:
    - name: demo-cpu-conteneur
      image: vish/stress
      resources:
        limits:
          cpu: "1"
        requests:
          cpu: "0.5"
      args:
        - -cpus
        - "2"
