apiVersion: v1
kind: Pod
metadata:
  name: demo-memoire
spec:
  containers:
    - name: demo-memoire-conteneur
      image: polinux/stress
      resources:
        requests:
          memory: "1000Gi"
        limits:
          memory: "1000Gi"
## kubectl apply -f pod-memoire.yaml
## kubectl get pod
## kubectl describe pod demo-memoire
## Warning  FailedScheduling  63s   default-scheduler  0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
## kubectl delete pod demo-memoire
