apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "monNomUtilisateurDocker",
          "password": "monMotDePasseDocker",
          "email": "monemail@example.com"
        }
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: mon-application
spec:
  containers:
    - name: app-container
      image: monregistryprive/monimage
  imagePullSecrets:
    - name: docker-registry-secret
## config map sur git no secret on git !
