apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  POSTGRES_PASSWORD: "monMotDePasse"

---
apiVersion: v1
kind: Pod
metadata:
  name: mon-application
spec:
  containers:
    - name: app-container
      image: monimage
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
