apiVersion: v1
kind: Secret
metadata:
  name: api-key
stringData:
  .api-key: "Ma super clé d'API"

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
    - name: app-container
      image: busybox
      command:
        - ls
        - "-la"
        - "/etc/api"
      volumeMounts:
        - name: api-key-volume
          mountPath: "/etc/api"
          readOnly: true
  volumes:
    - name: api-key-volume
      secret:
        secretName: api-key
## kubectl logs pods/secret-test-pod
